name: Scrape Omni Changelog & Demos

on:
  schedule:
    - cron: "0 9 * * 2"   # Every Tuesday at 9am UTC
  workflow_dispatch:
    inputs:
      force:
        description: "Force re-scrape all weeks"
        type: boolean
        default: false
      target:
        description: "What to scrape"
        type: choice
        default: both
        options: [both, changelog-only, demos-only]
      dry_run:
        description: "Dry run (no commits)"
        type: boolean
        default: false
      no_playwright:
        description: "Skip Playwright (faster, no YouTube URLs)"
        type: boolean
        default: false

concurrency:
  group: scrape-omni
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: pip install requests beautifulsoup4 lxml playwright

      - name: Install Playwright browsers
        if: ${{ github.event.inputs.no_playwright != 'true' }}
        run: python -m playwright install chromium --with-deps

      - name: Run scraper
        run: |
          ARGS=""
          [ "${{ github.event.inputs.force }}"         = "true" ] && ARGS="$ARGS --force"
          [ "${{ github.event.inputs.dry_run }}"       = "true" ] && ARGS="$ARGS --dry-run"
          [ "${{ github.event.inputs.no_playwright }}"  = "true" ] && ARGS="$ARGS --no-playwright"
          [ "${{ github.event.inputs.target }}"        = "changelog-only" ] && ARGS="$ARGS --changelog-only"
          [ "${{ github.event.inputs.target }}"        = "demos-only"     ] && ARGS="$ARGS --demos-only"
          python scraper/scrape_omni.py $ARGS

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet data/ && echo "changed=false" >> $GITHUB_OUTPUT || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push
        if: steps.changes.outputs.changed == 'true' && github.event.inputs.dry_run != 'true'
        run: |
          git config user.name  "omni-scraper-bot[bot]"
          git config user.email "omni-scraper-bot@users.noreply.github.com"
          git add data/
          git commit -m "chore: scrape $(date -u +%Y-%m-%d) [skip ci]"
          git push

      - name: Write step summary
        if: always()
        run: |
          if [ -f data/last_scrape_report.md ]; then
            cat data/last_scrape_report.md >> $GITHUB_STEP_SUMMARY
          else
            echo "No report generated." >> $GITHUB_STEP_SUMMARY
          fi
